### PR TITLE
feat: add from_service_account_info method to gen'd client surface

### PR DESCRIPTION
**Pull request by craiglabenz**
feat: add client_cert_source_for_mtls to grpc surface

### CODE REVIEW

**Comment by chrisrossi** [comment]
What is the difference between this and #318?

**Comment by craiglabenz** [comment]
Good question, @chrisrossi -- it's 11 days newer and hits 21 extra files, so I think it's basically the superset of #318.

**Comment by crwilcox** [comment]
As this doesn't appear to have any changes to synth.py, I closed the autosynth prs and am going to see if they reopen. The PRs via automation will bring commits with some context, and should break out the separate sources of gen. 🤞

**Comment by chrisrossi** [comment]
FWIW, I checked the box labelled "To automatically regenerate this PR, check this box." on #318, thinking it would do that, but AFAICT, it didn't do anything.

**Comment by crwilcox** [comment]
@chrisrossi yeah. it seems a bit odd. I did see that one of the PRs had a merge conflict, so not sure if that may have played into it.

**Review by crwilcox — APPROVED** [review]

**Comment by craiglabenz** [comment]
Covered by #322

**Pull request closed without merging**
