### PR TITLE
minor fixing

### LINKED ISSUE #409: indentation issue and lambda function should 'not in'
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-firestore/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

- identation issue
- and lambda function should ``not in``

#### Environment details

  - OS type and version: ``arch ( linux)``
  - Python version: `python 3.8.10`
  - pip version: `pip 20.0.2`
  - `google-cloud-firestore` version: `pip show google-cloud-firestore`

#### Steps to reproduce

  1. fixed indentation
  2. fixed lambda function

#### Code example

from
```python
lambda a: not a.keyword.value in self.CTRL_PARAMS,
```
to 
```python
lambda a: a.keyword.value not in self.CTRL_PARAMS,
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

### PR DESCRIPTION
**Pull request by slowy07**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-firestore/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #409  🦕

### CODE REVIEW

**Review by tseaver — COMMENTED** [review]
Thanks for the patch!  Unfortunately, both these files are generated code, and would need fixing up in their [source template](https://github.com/googleapis/gapic-generator-python/blob/master/gapic/templates/scripts/fixup_%25name_%25version_keywords.py.j2), rather than in this repository.

The whitespace and `lambda` fixes should be trivial to do there:  the `cst.Element` one, however, is apparently gnarly:  @software-dov has a comment there referring the the "log chipper" formatting which happens.

@busunkim96, @parthea could we perhaps run `black` over the `scripts/` directory via `owlbot.py` to make these fixes in place?

**Comment by slowy07** [comment]
> Thanks for the patch!  Unfortunately, both these files are generated code, and would need fixing up in their [source template](https://github.com/googleapis/gapic-generator-python/blob/master/gapic/templates/scripts/fixup_%25name_%25version_keywords.py.j2), rather than in this repository.
> 
> The whitespace and `lambda` fixes should be trivial to do there:  the `cst.Element` one, however, is apparently gnarly:  @software-dov has a comment there referring the the "log chipper" formatting which happens.
> 
> @busunkim96, @parthea could we perhaps run `black` over the `scripts/` directory via `owlbot.py` to make these fixes in place?

okay sorry for changes sir @tseaver

**Comment by parthea** [comment]
This was fixed in https://github.com/googleapis/gapic-generator-python/pull/963/ . We should see these changes in the next gapic generator update.

**Comment by slowy07** [comment]
> This was fixed in [googleapis/gapic-generator-python#963](https://github.com/googleapis/gapic-generator-python/pull/963) . We should see these changes in the next gapic generator update.

okay thanks @parthea !, and sorry for the change make mess up

**Pull request closed without merging**
