### PR TITLE
feat: add 'DocumentSnapshot.__repr__'

### PR DESCRIPTION
**Pull request by gieddy660**
…pshot

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-firestore/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Review by tseaver — COMMENTED** [review]
Thanks very much for the patch!

I find myself wondering whether the `__repr__` should include the snapshot's *metadata* (reference path, existence, create / read / update times) in addition to its *data*.

We likely also need one or more tests for the implementation.

**Comment by gieddy660** [comment]
Regarding the metadata, while useful information, I feel that showing it all might create too much of a mess (the two DatetimeWithNanoseconds alone take more than 150 characters).
I also agree taht some tests might be needed, but being somewhat inexpirienced I wouldn't really know what to actually test (after all I only added 2 lines, and DocumentSnapshot.to_dict() isn't all that complicated either).

**Comment by tseaver** [comment]
@gieddy660 
> Regarding the metadata, while useful information, I feel that showing it all might create too much of a mess (the two DatetimeWithNanoseconds alone take more than 150 characters).

Given that the *data* can be arbitrarily huge, I'm not sure how to judge.  @tswast do you have an opinion here?

**Comment by tswast** [comment]
> Given that the data can be arbitrarily huge, I'm not sure how to judge. @tswast do you have an opinion here?

I'm wary of including data in repr for privacy reasons as well. `repr` values are likely to end up in exceptions and logs.

With only minimal knowledge of Firestore, it seems to me that `reference` and `read_time` are actually the key / unique data importance to DocumentSnapshot and pose minimal privacy risk.

**Pull request closed without merging**
