### PR TITLE
feat!: Update Firestore to use Microgeneration

### PR DESCRIPTION
**Pull request by crwilcox**
/wip

### CODE REVIEW

**Comment by busunkim96** [comment]
@crwilcox What is the role of `test_pb2.py`? I don't see a proto file in https://github.com/googleapis/googleapis/tree/master/google/firestore/v1beta1

**Comment by crwilcox** [comment]
@busunkim96  These are used for cross_language test harnesses

**Comment by crwilcox** [comment]
Blocked on https://github.com/googleapis/gapic-generator-python/pull/485 for further test fixes. Since oneofs aren't being respected in the generator, many of the whichoneof calls are failing.

**Comment by crwilcox** [comment]
Closing this PR, continued in https://github.com/googleapis/python-firestore/pull/91

**Pull request closed without merging**
