### PR TITLE
feat: support more Python sequence types when encoding to Protobuf

### LINKED ISSUE #20: Support tuple when encoding to Firestore value
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**
When I save data to Firestore, it reject when the data contains tuple.

```py
  File "/env/local/lib/python3.7/site-packages/google/cloud/firestore_v1/_helpers.py", line 200, in encode_value
    "Cannot convert to a Firestore Value", value, "Invalid type", type(value)
TypeError: ('Cannot convert to a Firestore Value', (1, 12), 'Invalid type', <class 'tuple'>)
```
 **Describe the solution you'd like**

It should accept `tuple`. This is pragmatic because when I decide to submit data to Firestore, I no longer need to modify the content, so I leave it in a immutable type like `tuple`.

 **Describe alternatives you've considered**
Change the `encode_value()` function:

```py
    if isinstance(value, list):
        value_list = [encode_value(element) for element in value]
```
to this

```py
    if isinstance(value, (list, tuple, set, frozenset)):
        value_list = tuple(encode_value(element) for element in value)
```
 **Additional context**

### PR DESCRIPTION
**Pull request by hongquan**
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-firestore/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #20  🦕

### CODE REVIEW

**Comment by hongquan** [comment]
@googlebot I signed it!

**Comment by hongquan** [comment]
@BenWhitehead Could you please review?

**Comment by BenWhitehead** [comment]
@tseaver or @crwilcox Can either of you take a look at this and provide a review? This seems useful to me, but I'm not able to evaluate the code change toward the goal.

**Comment by crwilcox** [comment]
@hongquan would mind pulling in the upstream master and pushing again?

**Comment by hongquan** [comment]
@crwilcox I've just updated.

**Pull request merged**
