### PR TITLE
feat: add bulk writer

### PR DESCRIPTION
**Pull request by craiglabenz**
Adds the new BulkWriter feature, as assembled from these PRs:

* #368
* #375 & #397
* #384
* #413

### CODE REVIEW

**Comment by tseaver** [comment]
@googlebot I consent.

**Comment by tseaver** [comment]
@googlebot I consent.

**Comment by tseaver** [comment]
@googlebot I fixed it.

**Comment by tseaver** [comment]
@craiglabenz I give up on trying to appease @googlebot.

**Comment by crwilcox** [comment]
Code has been previously reviewed 👍

**Review by crwilcox — APPROVED** [review]

**Pull request merged**
