### PR TITLE
feat: SERVER_TIMESTAMP should survive deep copies (#820)

### LINKED ISSUE #820: SERVER_TIMESTAMP should survive deep copies (dataclasses.asdict)
## Problem

Currently `SERVER_TIMESTAMP` does not work if it has been copied via `copy.deepcopy`.
This is especially important for `dataclasses`.

Here is an example script to demonstrate the problem

```python
from google.cloud.firestore_v1.transforms import Sentinel
from google.cloud.firestore_v1.transforms import SERVER_TIMESTAMP
import dataclasses

@dataclasses.dataclass
class Example:
  timestamp: type[SERVER_TIMESTAMP] = SERVER_TIMESTAMP

example = Example()


assert example.timestamp is SERVER_TIMESTAMP

asdict = dataclasses.asdict(example)
assert asdict['timestamp'] is SERVER_TIMESTAMP
```

Currently the second assertion fails because the Sentinel has been deep copied.
```
Traceback (most recent call last):
  File "/Users/michael/dev/rfp-tool/test.py", line 15, in <module>
    assert asdict['timestamp'] is SERVER_TIMESTAMP
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

## Solution

The Sentinel class should define dunder `__copy__` and `__deepcopy__` methods.

```
diff --git a/google/cloud/firestore_v1/transforms.py b/google/cloud/firestore_v1/transforms.py
index f1361c9..ef0def8 100644
--- a/google/cloud/firestore_v1/transforms.py
+++ b/google/cloud/firestore_v1/transforms.py
@@ -26,6 +26,15 @@ class Sentinel(object):
     def __repr__(self):
         return "Sentinel: {}".format(self.description)

+    def __copy__(self):
+        # Sentinel identity should be preserved across copies.
+        return self
+
+    def __deepcopy__(self):
+        # Sentinel identity should be preserved across deep copies.
+        return self
+
+

 DELETE_FIELD = Sentinel("Value used to delete a field in a document.")
 ```
 
 I will send a PR attached to this issue.

### PR DESCRIPTION
**Pull request by mgraczyk**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-firestore/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #820

Please let me know if you expect additional tests.

### CODE REVIEW

**Comment by mgraczyk** [comment]
Fixed lint error with amend

**Review by daniel-sanche — APPROVED** [review]
LGTM, thanks for putting this together!

**Comment by daniel-sanche** [comment]
looks like you just need to pull in main

**Comment by mgraczyk** [comment]
Updated on top of main

**Pull request merged**
